### ISSUE TITLE
Representing Object Hierarchies

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#100]
If we wanted to model numerical computations in Julia with Catlab, we would need to represent the type hierarchy. My first thought is to add a morphism constructor to the doctrine like `subtype(A::Ob, b::Ob)::Hom(A,B)` which represents the fact that if `A <: B`, then you can cast an instance of A to an instance of B. Is that the best way to mode “order sorted algebras” within Catlab?

**Comment by epatters** [comment]
Here's how I implemented order-sorted algebra, on both objects and morphisms, for the Data Science Ontology:

https://github.com/IBM/semanticflowgraph/blob/e6ddc2115c75d4563b0e84592a89c7cb7466ef0c/src/Doctrine.jl#L66

I'll follow up later to elaborate on this.
