### ISSUE TITLE
Rendering a Theory/Presentation

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#134]
Now that we have the new unicode and axiom systems, it would be nice to be able to pretty print a theory or presentation. Once we start automatically constructing theories with GAT functors, this will be important for debugging.

1. As the macro you would write to create it. 
2. As a Latex representation that uses the latex versions of the unicode operators in the aliases.
3. As the wiring diagram you get with wiring_diagram(otimes(filter(is_hom, generators(P)))), which will be impractical for large presentations.

**Comment by epatters** [comment]
Subsumed by more specific issues #243 and #546. These are not yet resolved but the Gatlab prototype already has better pretty-printing of theories than the current Catlab.
