### ISSUE TITLE
Names of FinOrdFunctionLazy and FinOrdFunctionMap

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#184]
I'm having a hard time remembering these names and I think that the problem is that Lazy and Map aren't semantically related. I think we should use `FinOrdFunc` and `FinOrdVec` which are both subtypes of `FinOrdFunction` or we should use `FinOrdLazy` and `FinOrdEager`. Func vs Vec tells you about the storage mechanism and Lazy vs Eager tells you about the evaluation strategy. I'm ok encoding either one, but I think we should be consistent. What do you think?

**Comment by epatters** [comment]
I agree, the names are long and cumbersome. I'd prefer `FinOrdFunc` and `FinOrdVec`.

For consistency, similar changes should be made for the category **FinOrdRel**.
