### ISSUE TITLE
Pushout/pullback design

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#185]
I think we should change the pushout interface to return a type that supports accessing all the parts of the pushout construction. This will prevent the kind of abstraction leak we see in AbstractPetri.

```julia
struct Pushout{S}
    span::S
    coprod::Cospan
end

Pushout(s::Span) = Pushout(s, coproduct(s))
```

with methods

```julia
u(p::Pushout) = begin
    f,g = left(p.span), right(p.span)
    ι1, ι2 = left(p.coprod), right(p.coprod)
    return coequalizer(f⋅ι1, g⋅ι2)
end

Cospan(p::Pushout) = begin
    coeq = u(.coproduct)
    return Cospan(f⋅ι1⋅coeq, g⋅ι2⋅coeq)
end
```

**Comment by epatters** [comment]
Agreed. It turns out that describes (co)limits as a GAT leads to a similar design, see [here](https://github.com/AlgebraicJulia/Catlab.jl/blob/bfbbf81ee281c9268b7b1426c1d040aaef1513d0/src/theories/Limits.jl#L18).

**Comment by jpfairbanks** [comment]
We can also add the iteration interface to span and cospan so that `f,g = c` is defined to be `f,g = left(c), right(c)` since that seems to be a common idiom.

```julia
julia> struct Point
       a::Int
       b::Int
       end

julia> x,y = Point(1,2)
ERROR: MethodError: no method matching iterate(::Point)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:603
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:603
  iterate(::ExponentialBackOff) at error.jl:253
  ...
Stacktrace:
 [1] indexed_iterate(::Point, ::Int64) at ./tuple.jl:84
 [2] top-level scope at REPL[5]:1
```

We have to implement some of these methods: https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration-1

The alternative is to implement `Tuple(c::Cospan) = (left(c), right(c))` and then we would get `f,g = Tuple(c)` which requires less effort and matches the semantics of copsans better, they aren't really iterables, they are just pairs.

**Comment by olynch** [comment]
Did anyone start on this? This looks like a somewhat mechanical refactor once the interface is agreed on, so I think it would be good to expose me to more parts of the codebase.

**Comment by jpfairbanks** [comment]
I don't think so. @epatters did you have any attempt redoing the interface?

**Comment by epatters** [comment]
No, in part because I didn't want to conflict with Owen's work. Owen, I think this would be a great followup to what you've already done with n-ary (co)products.

**Comment by epatters** [comment]
I'll work on this issue and the related #171. I ran into the annoying iteration issue while working on #192.
