### ISSUE TITLE
Use StructArray for C-sets

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#209]
While reading this (hopefully not too dated) [comparison between JuliaDB and DataFrames](https://discourse.julialang.org/t/juliadb-dataframes-speculations-over-the-future-of-data-packages/14012/5?u=epatters), I realized that the design of C-sets is very similar to that of [`IndexedTable`](https://juliadata.github.io/JuliaDB.jl/latest/api/#IndexedTables.IndexedTable) in JuliaDB. `IndexedTable` is in turn implemented using the [StructArrays.jl](https://github.com/JuliaArrays/StructArrays.jl) package, [see here](https://github.com/JuliaArrays/StructArrays.jl#example-usage-to-store-a-data-table).

I suggest that we push this analogy further by unifying the fields `subparts` and `data` of `CSet`, of type `LabeledArray` and `NamedTuple` respectively, into a single field of type `StructArray`. Actually, we would need one of these for every object in C, so we would have a named tuple of struct arrays. We could then seamlessly treat a C-set as a collection of interlinked data tables, i.e., a database.

What does everyone think about this?

**Comment by olynch** [comment]
I've been thinking about data morphisms a bit lately, and it seems to me that they aren't best described by the presheaf formulation. It seems to me that a better description is this.

We start out with some index category $C$. A CSet without any data is an element of $\mathrm{Fun}(C,\mathrm{FinCard})$ (I am of the opinion that FinOrd only contains order-preserving morphisms). Then, to get a CSet with data, we let $D : \hat{C} \to \mathrm{Set}$ be the functor that takes a FinCard-valued presheaf $F$ to the set of "data decorations" on $F$ (i.e., the set of pairs of tuples of sets $A_i$ and morphisms from $F(c_i)$ to $A_i$), and the category of CSets with data is the category of elements of this functor.

A refinement of this is to fix the sets $A_i$. This is desirable to get the category of, say, $\mathbb{R}$-decorated graphs, or Petri nets with rates and initial values.

With this in mind, I think it *doesn't* make sense to combine the subparts and data fields of `CSet`, unless there is a more accurate way to think about `CSet`s in which the subparts and data are combined.

**Comment by epatters** [comment]
Maybe I haven't understood what is gained by the proposed change of perspective, but I actually like that C-sets/presheaves are a formalism that is "closed" under attachment of data attributes. It allows us to present a unified interface, built around standard categorical concepts, and to easily make contact with related ideas like databases and data frames. That the "ordinary morphisms" and "data morphisms" have to treated differently in implementation doesn't necessarily imply that we need to invent a new formalism, especially when that formalism seems to be nonstandard. In general, I think it is often important to *not* insist that the mathematics reflect all aspects of the implementation, because the implementation has to confront conceptually irrelevant problems such as the fact that infinite sets don't exist in computers.

I agree that the components of a C-set morphism corresponding to data should sometimes be restricted to identities on a fixed set. (But sometimes not!) This amounts to choosing a particular subcategory of the category of C-sets. We should probably support this in some form.

**Comment by epatters** [comment]
This is a good discussion to have because I think Spivak and collaborators faced similar issues in implementing functorial data migration. I'll follow up with more on that later.

**Comment by olynch** [comment]
If we are trying to make CSets close to presheaves, why do we have datatypes attached to data morphisms instead of datatypes attached to data objects?

**Comment by epatters** [comment]
That part is just wrong :) We should fix it.

**Comment by olynch** [comment]
Oh, OK. Will do :).

**Comment by olynch** [comment]
In that case, I was thinking that we could go even farther and unify the data and regular morphisms by having a type `FinCard(n::Int)`, which has a constructor that takes in `k` and errors if `k` is not in the range `1:n`.

**Comment by epatters** [comment]
Are you thinking a static type parameter here, `FinCard{n}`? Would this then have to be updated as you added more parts to the C-set?

As for the issue about `FinOrd` and `FinCard`, I see your point about `FinOrd` being confusing, although at least [Wikipedia](https://en.wikipedia.org/wiki/FinSet) has this usage. I haven't seen `FinCard` before. Is this a standard usage? Since the same issue comes up for `FinRel` and other categories, another approach would be to have a naming convention for the skeleta of categories, but then again `FinSetSkel` and `FinRelSkel` are pretty ungainly. So I dunno.

**Comment by olynch** [comment]
Yeah, it would have to be updated as you added more parts... I guess this is one of those times when implementation elegance should trump interface elegance, I don't think it's a good idea to update all of the types when you add a part.

RE: FinOrd vs. FinCard, if I were in a yak-shaving mood, I would probably argue for FinCard, but I don't care that much. I mainly said FinCard because we already have a FinOrd, and it's not a type.

I do have one more thing to say about my decorated presheaf idea: it seems to me that we only allow morphisms between non-data objects, or from a non-data object to a data object, and this is not captured in the standard presheaf formalism.

On the other hand, in the standard presheaf formalism if each finite set is a "table", then it makes sense to take "joins" by pullback along, say, a name morphism, because the codomain is the same, whereas this would not be as natural in the decorated case. So I think after bringing up again, I still agree with you.

**Comment by epatters** [comment]
Resolved by #219.
