### ISSUE TITLE
Category of Restricted Types

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Catlab.jl#223]
I propose that we have a category whose objects are `RestrictedTypes`

``` julia
struct RestrictedType
  T::DataType
  filter::Function # : T -> Bool
end
```

and where a morphism between `a` and `b` is a function `f` from `a.T` to `b.T` such that if `x : a.T` then `a.filter(x)` implies `b.filter(f(x))`.

This actually has products and coproducts (but not equalizers or coequalizers).

I can implement this in probably an hour if you all think it's a good idea. The inspiration for this was `PetriDecorator` in AlgebraicPetri.

``` julia
function (pd::PetriDecorator)(n::FinOrd)
    return p -> typeof(p) <: Petri && ns(p) == n.n
end
```

**Comment by epatters** [comment]
Resolved by #224. Thanks Owen!
