### ISSUE TITLE
Cleanup after next Julia LTS release

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#228]
Collecting here a list of things to fix after the next Julia LTS release.

**Comment by epatters** [comment]
I had to revert #174 to support Julia v1.0 (see #226). When the next Julia LTS is released and we can finally ditch v1.0, we should revert the reversion. That is, we should switch back to `Base.@kwdef` from Parameters.jl.

**Comment by epatters** [comment]
Remove all uses of `Compat`. The most common of these is for `isnothing`, a handy function added in Julia v1.1.

**Comment by olynch** [comment]
Use `fieldtypes` from Base in ACSets.

**Comment by epatters** [comment]
Support function application as an alternative syntax to `oapply`, introduced in #316.

**Comment by epatters** [comment]
In Julia 1.0, `nothing` cannot be `print`ed, leading to special cases in `show` for GAT exprs and possibly other types.

**Comment by epatters** [comment]
Revert [this line](https://github.com/AlgebraicJulia/Catlab.jl/blob/46602c6b64367993446212197a850656a7ce8c56/src/wiring_diagrams/Expressions.jl#L79) working around a bug in Julia v1.0, introduced in #371.
