### ISSUE TITLE
Use `<:` notation for extending GATs

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#234]
We're using the notation `Category(Ob,Hom) => MonoidalCategory(Ob,Hom)` for extension/inheritance of GATs. This Haskellism is a holdover from the days when we thought of GAT signatures as type classes, but it is un-Julian and it confuses everybody (including me).

Instead, we should use the Julia-style notation `MonoidalCategory(Ob,Hom) <: Category(Ob,Hom)` or maybe `MonoidalCategory{Ob,Hom} <: Category{Ob,Hom}`. For backwards compatibility, we can also keep around the old notation for some period of time.

**Comment by olynch** [comment]
I like the julia-style :curly, should we also change @syntax to be in line?

**Comment by epatters** [comment]
OK great, let's use curly for `@syntax` too, while also retaining the old syntax for awhile for backwards compatibility.

**Comment by olynch** [comment]
Should I add a deprecation warning to the old syntax?

**Comment by epatters** [comment]
Yes, let's issue a deprecation warning if possible. Is the source location being lost due to the metaprogramming in `@theory`? In the worst case, I figure it's better to have a deprecation warning with a wrong/missing line number than to have no deprecation at all.

**Comment by olynch** [comment]
Yes, the source location is available as `__source__` in the `@macro theory`, but I don't see how to get it in the regular function unless I manually pass it down, and I think that would be too clunky for just a deprecation warning. Should I just have a deprecation warning with no source location? i figure that would be better than giving the source location of the macro; that wouldn't be useful.

**Comment by epatters** [comment]
Agreed, let's keep this simple.

**Comment by epatters** [comment]
Resolved by #237.
