### ISSUE TITLE
Docs now take a very long time to build

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#247]
Since merging #219, there has been a massive jump in the build time for the docs, from [~10 min](https://github.com/AlgebraicJulia/Catlab.jl/runs/1049591809) to [one hour](https://github.com/AlgebraicJulia/Catlab.jl/runs/1053679623), as [reported here](https://github.com/JuliaDocs/Documenter.jl/issues/1261#issuecomment-684127355). I have no idea what is causing this or what to do about it.

**Comment by epatters** [comment]
By setting `JULIA_DEBUG=all` and building the docs locally, I can see roughly how much time `Documenter.Expanders` is spending on each file. It turns out that most of the time is spent not in the API docs but in Markdown files generated by Literate.jl. Most of these involve displaying wiring diagrams and have no intersection with #219 and involve no `@generated` code. This makes the sudden drastic slowdown all the more mysterious.

**Comment by olynch** [comment]
The intersection with #219 is that graphics uses the new property graphs...

I'll write some benchmarks for different ACSet operations (which is probably a good idea in any case), and we'll see if we can speed them up.

**Comment by olynch** [comment]
Or actually, I'll do some profiling first on the API docs.

**Comment by jpfairbanks** [comment]
Performance is one of my main concerns with ACSets right now. If they exercise the compiler in a big way, then we need to get involved with the Julia compiler team to get that pain point exposed before the 1.6 feature freeze or we will be living with slow Catlab for ~2 years on LTS Julia.

**Comment by olynch** [comment]
I have a hard time believing that the slow build is the compiler's fault; it must be a problem with my generated code. The only thing is, when I try to build the docs on my computer so that I can profile the build process, I get a SEGFAULT. I set up a docker container just like the docs.yml file, so I'm not sure what I'm doing wrong...

**Comment by epatters** [comment]
Try removing the `~/.julia/compiled` directory. Occasionally I've had to do this to resolve segfaults that seem to be related to caching problems.

**Comment by epatters** [comment]
Owen, thanks a lot for investigating. Based on my experiments last night, my current best guess is that there is a bad interaction involving the new ACSets implementation, the Julia compiler, and the specific [evaluation logic used by Documenter.jl](https://github.com/JuliaDocs/Documenter.jl/blob/2650d9391c742dc493e4ae7599ff34b4fe537b0d/src/Expanders.jl#L529). To summarize the above, here's what I'm seeing:

- There is no appreciable change to the runtime of test suite (8-10 min on GitHub CI)
- There is a large increase in the runtime of the docs, from ~10 min to 1 hr
- Most doc builds is spent running the Literate.jl notebooks
- Many of the notebooks should not exercise the C-sets code at all (e.g. the TikZ wiring diagrams) but are still executing very slowly

**Comment by olynch** [comment]
If it remade the @generated code every time it ran, that might do it; I definitely was prioritizing clarity over performance in the code that generates the functions, and there are a couple things that are quadratic that don't necessarily need to be. But they are quadratic in an $n$ that never gets above 10 in our code, so I thought it didn't really matter, especially because they *should* only run once, and the inner loop of the function that makes it technically quadratic is really fast. So I don't think that that is the problem...

**Comment by epatters** [comment]
I agree, I don't think there's anything obviously wrong with the code you `@generate`. As you can see from the linked issue, I've reported to Documenter.jl. I'm hopeful that with their help we can get to the bottom of it.

**Comment by epatters** [comment]
I think the discovered the problem or a large part of it. Issues have been filed upstream at https://github.com/JuliaDocs/Documenter.jl/issues/1438 and https://github.com/JuliaLang/julia/issues/38079.

**Comment by EricForgy** [comment]
Wild guess: 

Is there some type piracy going on in Catlab? The issue https://github.com/JuliaDocs/Documenter.jl/issues/1438 reminds me of the kind of thing you might see with precompilation invalidations that Tim et al have been working on. 

Maybe SnoopCompile.jl might help?

**Comment by epatters** [comment]
Thanks for the pointer, that could be helpful for debugging. My current guess is that it has something to do with generated functions but I really don't know. First, I'm going to hope that the experts at JuliaLang can weigh in :)
