### ISSUE TITLE
JSON serialization of attributed C-sets

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#265]
Serialize and deserialize attributed C-sets as JSON. Only the data in the `tables` field needs to be stored; the `indices` are redundant information.

To get started, we can assume that the data attributes are primitive JSON types, with perhaps special handling for `Symbol` vs `String`.

**Comment by jpfairbanks** [comment]
Yeah, it would be great to also convert the type of the ACSet into a https://json-schema.org/ so that you could get validation logic in other languages using these libraries https://json-schema.org/implementations.html

**Comment by epatters** [comment]
Serialization should be straightforward. For deserialization, I'd suggest the following procedure:

1. Add all parts of all types, without setting any subparts: `add_parts!(acs, type, n)`.
2. Set all subparts for all parts: `set_subparts!`

This should ensure that all the indices are rebuilt correctly.

**Comment by jpfairbanks** [comment]
@mehalter this is working for AlgebraicPetri, is there anything else we need to do on this issue?

**Comment by epatters** [comment]
Implementation started and reviewed at PR #372.

**Comment by mehalter** [comment]
I'll update that PR and get it ready for merging in the coming days! :D

**Comment by epatters** [comment]
Perfect, thanks!

**Comment by mehalter** [comment]
Just finished up fixing the comments on the PR, should be ready for some more review and hopefully merging 😃

**Comment by epatters** [comment]
Resolved by #372. Thanks @mehalter!
