### ISSUE TITLE
Generic version of substitute for extensions of UWDs

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#288]
## Summary
If we have an ACSet type that extends UWD by adding data attributes on the boxes, ports, and junctions, then we should be able to automatically derive the `substitute` implementation for that type. That would be really convenient for building operads over FinSetCospan aka Hypergraph Algebras, where the directed nature of Hom Expressions are cumbersome. 

## Background:
In the context of using hypergraph category expressions (or directed wiring diagrams) for terms of a hypergraph algebra, the user has to pick arbitrary divisions of the boundary into dom and codom, and then they have to add a bunch of terms to manipulate these doms and codoms (caps and cups) in their expression trees. The user has to do more work, and the data structures are bigger. The upside of that approach is that the Hom Exprs provide a manually created schedule for applying functions. The Hom Expr tells you the order in which to apply biased (binary) operators to apply the functor. Unfortunately, it is really inconvenient and it would be better if we allowed the user to express the pattern of interconnection using the `@relation` macro, and then supply any attributes for the boxes, junctions, and ports. This can currently be done by hand by using the ACSet data structure and writing the code that does the intended manipulations. 

## Substitution Approach
Another approach that would make it easy to express Hypergraph Algebras, would be to have a generic form of `substitute` that carried along all the data attributes of the boxes then the user would specify their term in the hypergraph algebra by a tree of substitutions and the application of FinSet functions to the outer ports of a subsystem. Substitute is currently implemented in [undirected.jl](https://github.com/AlgebraicJulia/Catlab.jl/blob/67e2333a2ec8a882b57577bc965c665014da88d2/src/wiring_diagrams/Undirected.jl#L254) and is the gnarliest code in the module. 

Let's use arbitrary UWDs to denote ACSets whose indexing category inherits from TheoryUWDs.

```julia
function substitute(f::UWD, indices::AbstractVector{Int},
                    gs::AbstractVector{UWD}) where {UWD <: AbstractUWD}
  @assert length(indices) == length(gs)
  h = UWD()
  copy_parts!(h, f, OuterPort=:)

  # Copy boxes from original diagram and diagrams to be substituted.
  gs_index = Vector{Union{Int,Nothing}}(nothing, nboxes(f))
  gs_index[indices] = 1:length(indices)
  for (i,j) in enumerate(gs_index)
    if isnothing(j)
      copy_parts!(h, f, Box=[i], Port=ports(f, i))
    else
      g = gs[j]
      copy_parts!(h, g, Box=boxes(g), Port=flat(ports(g, boxes(g))))
    end
  end

  # Add junctions obtained from pushout of junction sets.
  f_inner_junction = FinFunction(flat(
    junction(f, ports(f, i)) for (i,j) in enumerate(gs_index) if !isnothing(j)),
    njunctions(f))
  g_outer_junction = oplus([
    FinFunction(junction(g, outer=true), njunctions(g)) for g in gs ])
  f_leg, g_leg = colim = pushout(f_inner_junction, g_outer_junction)
  add_junctions!(h, length(ob(colim)))
  if has_subpart(h, :junction_type)
    # XXX: We should be taking the colimits in a slice category over the
    # junction attributes. That would automate this and also check for errors.
    set_subpart!(h, collect(f_leg), :junction_type, junction_type(f))
    set_subpart!(h, collect(g_leg), :junction_type,
                 flat(junction_type(g) for g in gs))
  end

  # Assign junctions to all ports.
  gs_incl = legs(coproduct([ FinSet(njunctions(g)) for g in gs ]))
  set_junction!(h, map(f_leg, junction(f, outer=true)), outer=true)
  set_junction!(h, flatmap(enumerate(gs_index)) do (i,j)
    if isnothing(j)
      map(f_leg, junction(f, ports(f, i)))
    else
      map(gs_incl[j] ⋅ g_leg, junction(gs[j]))
    end
  end)
  return h
end
```

## Questions
1. Since this code predates the completion of the Categorical Algebra and Structured Cospans of ACSets code, can we simplify this using these CategoricalAlgebra tools?
2. How does one write code that is generic in this way for example, "for all attributes of this part, preserve the attributes"?

## Proposed changes
If not, then it looks like all we need to do in here to generalize it to arbitrary UWDs is:
1.   Edit this code to preserve attributes of the boxes

```julia
# Copy boxes from original diagram and diagrams to be substituted.
  gs_index = Vector{Union{Int,Nothing}}(nothing, nboxes(f))
  gs_index[indices] = 1:length(indices)
  for (i,j) in enumerate(gs_index)
    if isnothing(j)
      copy_parts!(h, f, Box=[i], Port=ports(f, i))
    else
      g = gs[j]
      copy_parts!(h, g, Box=boxes(g), Port=flat(ports(g, boxes(g))))
    end
  end
```

2. change `add_junctions!(h, length(ob(colim)))` to preserve attributes, this should eliminate the special handling of `:junction_type` in this branch

3. change this code to preserve the attributes of the junctions, checking that the two big diagram and the set of small diagrams agree on all attributes of the junctions that are getting merged.

```julia
  # Assign junctions to all ports.
  gs_incl = legs(coproduct([ FinSet(njunctions(g)) for g in gs ]))
  set_junction!(h, map(f_leg, junction(f, outer=true)), outer=true)
  set_junction!(h, flatmap(enumerate(gs_index)) do (i,j)
    if isnothing(j)
      map(f_leg, junction(f, ports(f, i)))
    else
      map(gs_incl[j] ⋅ g_leg, junction(gs[j]))
    end
  end)
  return h
end
```

**Comment by epatters** [comment]
The good news is that, regarding proposed change 1, data attributes attached to boxes, ports, and outer ports will be preserved by `copy_parts!`. So if you don't need data attributes (besides `junction_type`) on junctions, you should be able to use `substitute` and `ocompose` with your custom UWD type today.

So this leaves two related problems, one about functionality and the other about design and code clarity. In terms of functionality, arbitrary data attributes on junctions should indeed be copied with appropriate error checking (proposed changes 2 and 3).

The design issue, which you raise in your questions, is how to cleanly express this so as to avoid writing lots of error-prone attribute munging code. The current code manually unpacks the wiring diagram into big FinFuctions, computes a pushout in FinSet, and then manually reconstructs a new diagram. It would be nice to do this using categorical constructions not in FinSet but in C-Set, where we already have appropriate handling of data attributes for colimits. Unfortunately, the substitution operation cannot simply be a pushout of C-sets because it involves "deleting" the boxes that are being substituted and pushouts of sets or C-sets cannot delete things (they can only merge them).

In DPO rewriting, you *can* delete things, with the deletion happening via pushout complement. I would hope that operad substitution can be phrased as a DPO rewrite of C-sets, but I haven't checked that it works. If it did, that would be a nice motivation to implement DPO!

**Comment by jpfairbanks** [comment]
> regarding proposed change 1, data attributes attached to boxes, ports, and outer ports will be preserved by copy_parts!

Does/should copy_parts! preserve the Hom fields?

> Unfortunately, the substitution operation cannot simply be a pushout of C-sets because it involves "deleting" the boxes that are being substituted, but pushouts of sets or C-sets cannot delete things (they can only merge them).

What if we did something else with the boxes that are supposed to get deleted and instead keep them around to keep track of subsystems. Could we solve two birds with one stone here? We would like the composite UWD to keep track of the hierarchical composition that you used to create it (for visualization purposes) but we want that in a way that is inconsequential for the semantics/interpretation and could be stripped out later.

**Comment by epatters** [comment]
> Does/should copy_parts! preserve the Hom fields?
>

I'm not sure I understand the question, but assuming the `Hom` attribute is attached to the boxes, yes, it will be preserved.
> 
> What if we did something else with the boxes that are supposed to get deleted and instead keep them around to keep track of subsystems. Could we solve two birds with one stone here? We would like the composite UWD to keep track of the hierarchical composition that you used to create it (for visualization purposes) but we want that in a way that is inconsequential for the semantics/interpretation and could be stripped out later.

That's an interesting idea. It wouldn't be operadic composition anymore, but it would be a different operation that tracks the hierarchical construction of the diagram, which as we've discussed before could be very useful to avoid having to reconstruct the hierarchy that existed in the first place.

**Comment by jpfairbanks** [comment]
This might be obvious, but can you write hypergraph morphism composition of UWDs as structured cospans where the interface object is the OuterPorts?
