### ISSUE TITLE
Indexing notation for presentation generators

### ISSUE THREAD

**Issue by mehalter** [AlgebraicJulia/Catlab.jl#301]
It would be great to support indexing notation to access presentation generators instead of having to call `generators` to set variables. To do something like

```julia
@present Epi(FreeBiproductCategory) begin
  (S,I,R)::Ob
  inf::Hom(S⊗I,I)
  rec::Hom(I,R)
end

sir = Epi[:inf] ⋅ Epi[:rec]
```

**Comment by epatters** [comment]
Implemented with broadcasting so you can also write:

```julia
inf, ref = Epi[[:inf,:rec]]
```
