### ISSUE TITLE
Requirement of id2 and compose for both vertical and horizontal morphisms for Double Category Instance

### ISSUE THREAD

**Issue by shivamkhare95** [AlgebraicJulia/Catlab.jl#304]
The current Catlab code raises an error if id2H, id2V, composeH and composeV are not defined for both horizontal and vertical morphism classes.

Example:
For this instance:
```
@instance DoubleCategory(NeuralNetDom, NeuralNet, Discrete, SquareDiagram)
```
The following error is raised:
```
ERROR: LoadError: Method id2V(f::NeuralNet) not implemented in mod instance
```

**Comment by epatters** [comment]
This issue should no longer be relevant once the GAT for double categories has been refactored (now in progress).
