### ISSUE TITLE
Should we use `Base.view` for `subparts`?

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#307]
From the definition of `subpart`:
```julia
subpart(acs::ACSet, part, name::Symbol) = subpart(acs,name)[part]
subpart(acs::ACSet, name::Symbol) = _subpart(acs,Val(name))
```
we can see that when you call `subpart(acs, name)` you will get a reference to the array, which means that mutation of `acs` will be visible to callers of `subpart`, but when you index a with `part` in the method `subpart(acs, part, name)` you will get a copy because of the julia semantics of indexing. I think we should be consistent and always return copies or always return [views](https://docs.julialang.org/en/v1/base/arrays/#Base.view). In this case, we would have the definition:

```julia
subpart(acs::ACSet, part, name::Symbol) = view(subpart(acs,name, part)
subpart(acs::ACSet, name::Symbol) = _subpart(acs,Val(name))
```

If you wanted to get the part as a contiguous array, you could call collect 

```julia
julia> view([1,2,3], [1,3]) |> collect
2-element Array{Int64,1}:
 1
 3
```

I think there is very little downside to using views, and lots of reductions in memory allocation, since we are minimizing copying.

**Comment by epatters** [comment]
Good point. Let's consistently use views.

**Comment by epatters** [comment]
Question: I assume we should make an exception for the case of scalar indexing, since zero-dimensional views will be annoying:

```julia
julia> x = view([1,2,3], 2)
0-dimensional view(::Array{Int64,1}, 2) with eltype Int64:
2

julia> x + 1
ERROR: MethodError: no method matching +(::SubArray{Int64,0,Array{Int64,1},Tuple{Int64},true}, ::Int64)
```

**Comment by jpfairbanks** [comment]
Seems reasonable because there are no memory savings in that case. although people should be using broadcasting to handle the Vector case correctly, right?
