### ISSUE TITLE
Tikz (to_tikz) does not render some labels 

### ISSUE THREAD

**Issue by sjbreiner** [AlgebraicJulia/Catlab.jl#312]
I noticed that greek letters aren't showing up in tikz wiring diagrams. Similarly, unicode like \otimes is not rendered.

**Comment by epatters** [comment]
Currently no effort is made to translate Unicode symbols into their LaTeX counterparts, so if your symbols are Unicode, I figure that they will only show up properly if LaTeX is configured to support Unicode.

One thing that you can always do is put the LaTeX commands directly into the generator names, e.g.

```julia
α = Hom("\\alpha", X, Y)
```

This is a bit hacky but it works. I wonder if Julia's builtin LaTeX -> Unicode table could be reverse-indexed to do this more automatically?

**Comment by epatters** [comment]
Going to close this for now. Feel free to ping me or the catlab channel if you can't get this working.
