### ISSUE TITLE
Conventions on ACSet schemas in standard library

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#331]
The schemas for C-sets included in Catlab, mainly in `Catlab.Graphs` and `Catlab.WiringDiagrams`, are not currently publicly exported. This means that we're allowed to change them as we please, but it also means that they must be manually imported and users cannot reliably build on them. IMO, the schemas are as much a part of the interface as the data types they generate and so we should export them.

Beyond that, there is a question of naming convention. So far I've been a bit scattered: in Catlab itself, I use the prefix `Theory` but in blog posts and presentations I've been using `Schema`. We should pick one and use it consistently. My preference is currently for `Schema` because

- it matches the GAT (`Schema`) and default syntax (`FreeSchema`)
- the idea of a schema is familiar from databases and software engineering
- category theorists and logicians will get the connection to categorical logic implied by `Theory` but this use of "theory" will probably seem weird to everyone else

Thoughts on this?

**Comment by olynch** [comment]
I'm in favor of the `Schema` convention, and also definitely in favor of exporting acset schemas!

**Comment by epatters** [comment]
Great, let's do it then.

**Comment by jpfairbanks** [comment]
Yeah I think Schema is better, but could we abbreviate it as `Sch`? Some of the schema names are really long. I'm looking at you `SchemaSymmetricCircularPortGraphs` 👀
