### ISSUE TITLE
Attributed Sets

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Catlab.jl#338]
For a couple reasons, I think it would be a good idea to have a dedicated type for Attributed Sets that are "backed by" an Attributed C-set. In practice, this would look like

```julia
struct AttributedSet{A <: ACSet, P}
  backing :: A
  parts :: Vector{Int}
end
```

So for instance, if we have

```julia
g = @acset Graph begin
   E = 4
   V = 4
   src = [1,2,3,4]
   tgt = [2,3,4,1]
end
```

Then `AttributedSet{Graph,:E}(g,[2,4])` would represent the data frame

| src | tgt |
|---|---|
| 2 | 3 |
| 4 | 1 |

This is useful for several reasons.

1. It's more straightforward to implement limits in this setting, and then general limits can be reduced to this case.
2. Lots of data science operations only make sense on attributed sets, not attributed c-sets. (see: #335)
3. This is a good thing for a query to return, when we eventually figure out querying.

More generally, it might be interesting to have "views" of ACSets in any shape, just like we can have views of arrays without copying. But I think we should start with AttributedSets.

I'm going to get started on this, but, as always, the earlier I get input on this the easier it is to change things!

**Comment by epatters** [comment]
Good idea. I would definitely support something like this.

Ideally, we can write generic code that supports any `AbstractArray{NamedTuple{...},1}` conforming to the Tables.jl interface, such as the tables in TypedTables:

```julia
struct Table{T <: NamedTuple, N, Data <: NamedTuple{<:Any, <:Tuple{Vararg{AbstractArray{<:Any,N}}}}} <: AbstractArray{T, N}
    data::Data
end
```

Views of the ACSets fit this pattern, as well as things liked TypedTables and StructArrays.

One place where "attributed sets" are already used is in the feet of structured cospans when the boundary object has data attributes. See [`ACSetTableType`](https://github.com/AlgebraicJulia/Catlab.jl/blob/7c02e283a36569d89585215021322025e4e36dc8/src/categorical_algebra/CSetDataStructures.jl#L113) and the `StructuredCospans` module. So whatever framework we come up with for attributed sets should accommodate this use case as well.

**Comment by olynch** [comment]
I did not know about ACSetTableType! Very interesting. One subtlety is that an ACSet type generated by ACSetTableType is actually sensitive to schema presentation; i.e. it looks to me like it does not copy over compound attributes that "leave" the single object. So if you are looking at a schema for graphs where the nodes are decorated, then `compose(:src, :dec)` is not an attribute on the single table for ACSetTableType, but it is an attribute on edges.

Not cataclysmic, but worth looking out for. Also, this may be the desired behavior some of the time! I.e., in a structured cospan setting, you may want the feet to only have a subset of the possible attributes!

I definitely like the idea that AttributedSet could implement the AbstractArray{NamedTuple{...},1} type. However, is it possible to do this without the mutating methods? Those might be problematic.

**Comment by jpfairbanks** [comment]
I agree this is a good direction to explore. For mutation, you can always implement setindex(t::T, x,I) = error("Ts are immutable arrays") to get a runtime error for mutation. StaticArrays.jl might have a convention for this type of error condition

**Comment by epatters** [comment]
> I did not know about ACSetTableType! Very interesting. One subtlety is that an ACSet type generated by ACSetTableType is actually sensitive to schema presentation; i.e. it looks to me like it does not copy over compound attributes that "leave" the single object.

You are right, the intended use case was for structured cospans, where in the main examples you take objects with no nontrivial outgoing morphisms, like vertices in a graph or places in a Petri net. Maybe eventually we'll want consider objects that do have outgoing morphisms, in which case we'll need to extend the structured cospans machinery a bit.

As for being presentation dependent, that's true, but then again everything about our C-sets implementation is :)

> For mutation, you can always implement setindex(t::T, x,I) = error("Ts are immutable arrays") to get a runtime error for mutation. StaticArrays.jl might have a convention for this type of error condition

ACSets now implement [`setindex!`](https://github.com/AlgebraicJulia/Catlab.jl/blob/387d4b4d480c145fbb8b432614f0444e9e77ce90/src/categorical_algebra/CSetDataStructures.jl#L565) as an alias for `set_subpart!`, so we could support `setindex!` for view on an ACSet by delegation to the underlying ACSet.

**Comment by epatters** [comment]
Going to close this issue since the basic functionality is implemented and merged. If enhancements are needed, we can open new issues.
