### ISSUE TITLE
ACSet macros

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#339]
Should we extend the DSL Owen came up with to allow specification of ACSetTransformations?

**Comment by epatters** [comment]
I don't know, maybe. What did you have in mind?

If `g` and `h` are graphs, you can already do

```julia
CSetTransformation((V=[...], E=[...]), g, h)
```

or

```julia
CSetTransformation(g, h, V=[...], E=[...])
```

and the vectors will be coerced to `FinFunction`s.

**Comment by jpfairbanks** [comment]
I guess a CSet morphism is determined by a FinFunction for each object in C, so then that constructor is simple enough. 

I was thinking about specifying g, h and the Homomorphism all at once. Like if g is a sub graph of h as encoded by an injective hom, there is a ton of redundancy In specifying them separately.

**Comment by epatters** [comment]
I see, yes, it would definitely be useful to have a function that constructs a sub-C-set and the inclusion morphism all at once.

**Comment by epatters** [comment]
Closing in lieu of #349.
