### ISSUE TITLE
A Radically Different Acset Implementation

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Catlab.jl#375]
There are some problems with the current Acset implementation.

1. The generated types are, to put it lightly, a Lovecraftian horror. Looking at error messages for them is *awful*.
2. The way that we put all of the type parameters into the type is a massive hack, and not extensible to, say, allowing for equations in the type, which we might want later down the road.
3. The support for "subtyping" is extremely janky.

Here is my proposal for fixing this. Instead of fixing the parameters to one generic acset type, `ACSetType(TheoryGraph)` should declare a new struct type that subtypes `AbstractACSet` and implements `schema(::Type{Graph})`, which returns the `FreeSchema` associated to `Graph`. Obviously, it then needs to be a macro.

Then all of our `@generated` methods can apply to any struct that subtypes `AbstractACSet` and implements `schema(::Type{Graph})`, as long as we lay out the data in each generated struct in some logical way that corresponds to the schema.

In fact, the current acset implementation could be subsumed by this, by writing a `schema(::Type{ACSet{CD,AD}})` method.

This also decouples the `@generated` methods from the data storage; in theory we could write a *bespoke* implementation for a certain acset that took advantage of some domain-specific features, but then still have all of the `@generated` methods as long as we were careful to lay out the data in a certain way.

This solves 1 because stack traces now use the name of the generated struct, so `Graph` would show up as `Graph`.

This solves 2 because the schema is no longer stored in the type, it is returned by a method on the type.

This solves 3 because we can now have `DecoratedGraph` subtype `AbstractGraph`, if `@ACSetType` looks at the ancestor of the schema, or if we just manually add a parameter to `@ACSetType` telling it which type to subtype when it generates the struct and/or associated abstract type.

This may even have performance benefits, if Julia can specialize code more effectively for custom struct types.

**Comment by jpfairbanks** [comment]
This sounds like it is shifting stuff from generated function compile time to macro time, which allows for more flexibility especially around manipulating names of stuff for the error messages. We definitely need to benchmark compile times before and after this change. @mehalter and @bosonbaas are reporting long precompiled times from AlPetri so we definitely don't want to make things worse. I think the benefits to error reporting and subtyping would be big wins that offset a small increase in compile times.

**Comment by olynch** [comment]
Is it possible, or will it eventually be possible, to do something with `precompile` to help with this? https://julialang.org/blog/2021/01/precompile_tutorial/

**Comment by epatters** [comment]
The title of this issue had me worried but it's not *that* radical :) I think we've discussed something along these lines before.

Anyway, thanks for making the argument and starting an implementation. Besides improving the error messages, the ability to exert more control over the subtype hierarchy would be really nice. So I like the approach.

I agree with James that we'll want to do benchmarks. One downside to the benchmarks in this repo is that they don't count precompile time! Hopefully precompile can help. I don't know much about it.

**Comment by olynch** [comment]
When I was out walking today, it occurred to me that, while we were making changes, we could store each hom/attr as a FinFunction/FinDomFunction, whose domain could be any FinSet; i.e. not just FinSet{Int,Int}.

Also, we could simplify a lot of code if we made an "IndexedFinDomFunction" type, put all of the keeping track of indices inside that, and then had a simple interface for it.

This might get rid of the really cool feature of being able to use any Table as storage though... Thoughts?

**Comment by jpfairbanks** [comment]
Could your IndexedFinDomFunction support iterating over named tuples? In that case it would match the table interface.

**Comment by olynch** [comment]
So, this would still be able to *implement* the Table interface. It's just that we couldn't use anything that implemented the Table interface *inside* the ACSet.

**Comment by jpfairbanks** [comment]
I like being able to use arbitrary backing storage because then we can have GPUACSets and DistributedACSets with the same interface

**Comment by olynch** [comment]
On the other hand, maybe the tables interface is the wrong way to do this; maybe we need DistributedFinDomFunctions! In fact, it kind of makes sense for any AbstractArray to be used in a FinDomFunction.

I just can't wait until we do colimits on the GPU...

**Comment by olynch** [comment]
(I know that actually doesn't make sense, but it would be funny)

**Comment by jpfairbanks** [comment]
All of these options are worth exploring. Colimits on GPU would be awesome. UnionFind for GPU is probably pretty fast because it does graph connected components.
