### ISSUE TITLE
Acset Interface

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Catlab.jl#381]
This idea was floated a while ago, but I think that while we're making this new StructAcset implementation, we should take the time to actually make an interface for acsets, so that we can have multiple implementations. This would also support dynamic acsets, and whatever other kinds of specialized implementations we want.

The interface should:
- Have a method to return the schema when called on a value
- Have a method to return the schema when called on a type
- Have a method on the type that says whether or not the schema is inferrable from just the type.
- Have a method that says whether it is read only, write only, or read/write.
- Provide raw access to the obs/homs/attrs/indices
- Have set/get/delete for parts/subparts that automatically deals with indexing.

We could also have default implementations for get/set/delete parts/subparts that used the schema and the raw access methods. These could be `@generated`, looking up the schema at runtime if the schema was not inferrable from the type.

The read only, write only, or read/write distinction comes from an idea that I just had, where we can use schema inclusions to make a read-only wrapper implementing Graph out of a SymmetricGraph, and a write-only wrapper implementing SymmetricGraph out of a Graph.

**Comment by epatters** [comment]
For the record, this was handled in the struct acsets refactor.
