### ISSUE TITLE
getproperty type piracy

### ISSUE THREAD

**Issue by mohamed82008** [AlgebraicJulia/Catlab.jl#382]
Hi,

I would like to draw your attention to a type piracy that Catlab has in its definition of `getproperty`. This is causing a slowdown in surprising ways in Julia. Ref: https://github.com/JuliaLang/julia/issues/39534

**Comment by epatters** [comment]
Thanks for reporting this. We'll look into fixing it.

**Comment by epatters** [comment]
@olynch, we should address this. I suggest that we just eliminate the `getproperty` overrides for C-set types and replace them with accessor functions, e.g., `CD.ob` would become `ob(CD, ...)`. Definitely no type piracy there since we own those functions.
