### ISSUE TITLE
Incompatible with ancient graphviz

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#387]
Ancient graphviz 2.38 (released in 2014) fails spectacularly when rendering things of shape "plain"

<img width="769" alt="Screen Shot 2021-02-25 at 11 03 31 AM" src="https://user-images.githubusercontent.com/2753998/109180790-3e8aa380-7759-11eb-8dcb-55baf9a77927.png">

Not sure that we should try to support such an ancient graphviz version, but maybe working with a minimum graphviz version of 2.42 or something would be reasonable.

**Comment by epatters** [comment]
Yeah, we should probably find the minimum version that works and document what version that is.

**Comment by jpfairbanks** [comment]
Yeah `#wontfix` hardcore. I was looking for a workaround, but the cluster admin installed graphviz 46.1 faster than I could change the node shapes. I think we could all run `dot -V` and take the minimum over all catlab devs to get the minimum supported version

**Comment by epatters** [comment]
The 2.46 series is very recent. I am pretty sure that 2.42 (first release July 2019) has always worked, so maybe we should just go with that.
