### ISSUE TITLE
Docs fail to build without luatex

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#396]
Can we set it up where the docs continue to build without these images, but trigger a build failure for CI? 

```
[ Info: executing notebook `layouts_vs_drawings.ipynb`
┌ Error: error when executing notebook based on input file: `~/github/AlgebraicJulia/Catlab/docs/literate/graphics/layouts_vs_drawings.jl`
└ @ Literate ~/.julia/packages/Literate/kB2Gm/src/Literate.jl:609
ERROR: LoadError: IOError: could not spawn `lualatex --enable-write18 --output-directory=./jl_uk5js5 ./jl_uk5js5/tikzpicture.tex`: no such file or directory (ENOENT)
Stacktrace:
```

**Comment by epatters** [comment]
I wouldn't ignoring errors to be the default configuration, but I suppose we could add a flag to our `make.jl` that would ignore errors. I don't see any flags in Documenter or Literate that would help with this, so we'd have to manually catch the errors.

All in all it seems like a hack and if we're going to do hacks, you may as well just comment out the part of `make.jl` that the runs the Literate files.

**Comment by jpfairbanks** [comment]
That is what I ended up doing! I also discovered that you can get debugging info out of documenter with 

JULIA_DEBUG=Documenter as an environment variable.

**Comment by epatters** [comment]
I've also had to comment out that block before. I suggest that we add a flag `--no-literate` to `make.jl` that will cause that block to be skipped, which would be more convenient than manually commenting it.

**Comment by jpfairbanks** [comment]
That would be helpful and it should probably remind you to remove the docs/src/generated folder, I had to remove that by hand and was very conflicted removing a folder in src that was called generated. Had to check the gitignore to make sure it was actually generated.
