### ISSUE TITLE
DPO rewriting of structured multicospans

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#447]
PR #425, partially merged in #446, contains a preliminary implementation of DPO rewriting of structured cospans. I think we can make it simpler, while also making it more general, by doing a couple things.

First, although multicospans seem harder than cospans, in practice they often lead to cleaner code. When working with cospans, you have to deal with the apex and then the two feet, which typically requires three statements, two of which are nearly identical. With multicospans, you deal with the apex and then map over the feet, effectively requiring only two statements. Moreover, experience shows that the extra flexibility of multicospans is often very useful in applications. So we should implement DPO rewriting in this setting.

Second, the diagram comprising a rewrite rule of structured cospans is not an arbitrary diagram with 9 vertices; it has a special structure, being a span of structured cospans. Preserving this mathematical structure in the data structures should lead to more understandable code.

To be more concrete, I propose the following plan:

1. Create a data structure for morphisms of structured multicospans (with the same number of legs). Such a morphism consists of a morphism in X between the apexes and, for each pair of feet, a morphism in A, such that all the squares commute. This should result in new types `Structured(Multi)CospanHom` in the `StructuredCospans` module.

2. Create a new type `OpenRewriteRule` that is a span of structured multicospans, possibly just as a type alias involving `Span` and `StructuredMultiCospanHom`.

3. Implement open DPO rewriting using these rules as input.

**Comment by kris-brown** [comment]
These issues were addressed in AlgebraicRewriting.jl
