### ISSUE TITLE
`@acset` macro not interacting well with unique_indexed

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/Catlab.jl#502]
ACSets that are created with the `@acset` macro can generate acset instances that violate the uniqueness condition (because it seems to be accessing random bytes of memory). E.g.

```julia
@present TheoryLabeledGraph <: TheoryGraph begin
  Label::AttrType
  label::Attr(V,Label)
end
@acset_type IndexedLabeledGraph(TheoryLabeledGraph, index=[:src,:tgt],
                                unique_index=[:label]) <: AbstractGraph

z=@acset IndexedLabeledGraph{Int} begin V=7 end
z[:label]

 5271426576
          3
     296964
          3
          4
          0
          0
```

It should probably fail if the unique attributes are not specified.

**Comment by epatters** [comment]
Because integer vectors cannot be `undef`, I agree that the correct behavior here is probably to fail with an error that the unique-indexed attribute was not initialized.

In the original acset implementation, I was at some pains to try to deal with the subtle issues around initialization and indexing. It's tricky.

**Comment by epatters** [comment]
This issue seems to have been resolved by the most recent acsets refactor:

```text
@acset_type IndexedLabeledGraph(SchLabeledGraph, index=[:src,:tgt],
                                       unique_index=[:label]) <: AbstractGraph
z=@acset IndexedLabeledGraph{Int} begin V=7 end
IndexedLabeledGraph{Int64} with elements V = 1:7, E = 1:0
┌───┬─────────┐
│ V │   label │
├───┼─────────┤
│ 1 │ nothing │
│ 2 │ nothing │
│ 3 │ nothing │
│ 4 │ nothing │
│ 5 │ nothing │
│ 6 │ nothing │
│ 7 │ nothing │
└───┴─────────┘
```
