### ISSUE TITLE
Suggestion - Open Discussions for asking questions

### ISSUE THREAD

**Issue by VarLad** [AlgebraicJulia/Catlab.jl#560]
It'd be convenient to be able to open discussions for asking questions
I can ask them on Slack, but they'll disappear, and Discussions add more visibility to the questions

**Comment by jpfairbanks** [comment]
I've never used Github discussions before, but it does seem like a good tool for a little stack exchange for catlab. I bet my students would populate it with Q&A while working on their projects. @epatters any objection to enabling GH discussions on here? 

@VarLad, there is also the catlab stream in the julia zulip, which is more permanent and also organized into threads.

**Comment by epatters** [comment]
I've never used GitHub Discussions but it seems like a promising feature, so let's see how it goes! I've turned it on.

> Also, I'd like to contribute a small tutorial to the docs Need some help on it though I'm stuck on how to use `Catlab.Syntax.functors` for substitution
> 
> Catlab could _really_ use some better docs and some tutorials

Any contributions along these lines would be very welcome. Thank you!

It is worth mentioning that Catlab does have additional materials that can serve as docs scattered across different places, especially the [AlgbebraicJulia blog](https://www.algebraicjulia.org/blog/). @TheCedarPrince may be helping us organize these materials in a more coherent and accessible way.

**Comment by TheCedarPrince** [comment]
@VarLad - we can connect more on this later.
Let's discuss on Zulip. :)
