### ISSUE TITLE
Missing documentation for @acset_type’s

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/Catlab.jl#561]
Objects defined using the macro `@acset_type` are missing from the official documentation for projects that use Catlab v0.13.0.

For example, `Catlab.Graphs.BasicGraphs.Graph` is missing in the [v0.13.3 Catlab docs](https://algebraicjulia.github.io/Catlab.jl/v0.13/apis/graphs/) but is present in the [v0.12 Catlab docs](https://algebraicjulia.github.io/Catlab.jl/v0.12/apis/graphs/).

For example, `DeltaSet2D`, `EmbeddedDeltaSet1D`, and `EmbeddedDeltaSet2D` are missing in the current [CombinatorialSpaces.SimplicialSets docs](https://algebraicjulia.github.io/CombinatorialSpaces.jl/dev/simplicial_sets/)

It should be noted that the documentation for `DeltaSet1D` is built correctly, even though it is simply defined as `const DeltaSet1D = Graph`, and `Graph`’s documentation is not built correctly.

I looked at the [diff](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/commit/d1354babd3eb8fd22d0a2051ad2edaf90fc64aef#diff-e698afd99f8184c8272e173a4dcd04d5b6c4b2e2c4ce149e65e944557a2075ba) of simplicial_sets/index.html for the most recent build of the docs (based on [4b8db1b](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/tree/4b8db1b2439d02dbcb15f19dc2872e98e50ac140)) and saw that DeltaSet2D was there in the previous commit, but got cut out by this commit from September 30, 2021. I believe this issue has been present since that day.

**Comment by epatters** [comment]
Thanks for the report. It look like the `@acset_type` macro is not attaching the docstring to the generated struct. It is certainly possible to do that because macros can control where docstrings attached to the macrocall go.

@olynch, do you have the bandwidth to fix this?

**Comment by epatters** [comment]
Closed by #594.
