### ISSUE TITLE
Style of individual boxes in Tikz output

### ISSUE THREAD

**Issue by nathanielvirgo** [AlgebraicJulia/Catlab.jl#643]
I'm not sure if this is a feature request or a question. (If there's a better place to ask questions, please let me know.)

In `Catlab.Graphics.TikZWiringDiagrams.to_tikz` it's possible to change the style of all boxes by passing a `styles` Dict, and it's possible to change the shape of individual boxes by using the `box_shapes` argument. But is it possible to change the style of individual boxes in any other way? For example, what if I want to shade different boxes in different colours, or to give some boxes rounded corners and others not - is it possible to do that?

If that's not possible, would it be possible to add it as a feature?

**Comment by epatters** [comment]
It's fine to ask questions here, especially if they might actually be feature requests. If you want to have more discussion, you can also find us on catlab.jl channel of the [Julia Zulip](https://julialang.zulipchat.com/).

In this case, I believe the `box_styles` keyword argument will do what you want. Unfortunately, it's use is not illustrated in the [docs](https://algebraicjulia.github.io/Catlab.jl/dev/generated/graphics/tikz_wiring_diagrams/#Custom-styles).
