### ISSUE TITLE
(Co)limits with loose acset transformations with fixed type components

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/Catlab.jl#680]
Particularly in the context of DPO rewriting with attributes, we want to perform (co)limits with loose acset transformations. In particular, this should be tractable when the `type_components` of the derived projection/inclusion maps are provided ahead of time, with the possibility of a runtime error if this would lead to inconsistent results.

**Comment by kris-brown** [comment]
This is addressed in a draft PR https://github.com/AlgebraicJulia/Catlab.jl/pull/682

**Comment by epatters** [comment]
The underlying need will be addressed by #740, right?

**Comment by kris-brown** [comment]
Right!
