### ISSUE TITLE
JSON serialization for ACSets should include the IDs of the parts

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Catlab.jl#695]
When we eventually implement sparse ACSets, the part numbers will no longer be 1:n, and so we should forward-proof our serialization to eventually support this.

**Comment by aaguinal** [comment]
I'm trying to figure out what an example would like look when the IDs of the parts are not 1:n. For this example, would that mean that `V` and `E` below would be replaced by a struct that contains unique IDs and labels for each vertex and edge?

```julia
Catlab.Graphs.BasicGraphs.Graph:
  V = 1:5
  E = 1:4
  src : E → V = [5, 5, 5, 5]
  tgt : E → V = [1, 2, 3, 4]
```

**Comment by epatters** [comment]
Right, the idea is that we will support IDs that are not contiguous integers from 1 to n, but could be non-contiguous integers or symbols, e.g.

```julia
Graph:
  V = Set([:x, :y, :z])
  E = Set([:f, :g])
  src =  Dict(:f => :x, :g => :y),
  tgt = Dict(:f => :y, :g => :z)
```

To handle this, we should include the IDs as a special key, say `_id`, in the JSON object for the entity.

**Comment by aaguinal** [comment]
Do you think this will also be the case for `AttrType`?

**Comment by epatters** [comment]
Nope, because the elements corresponding to objects are arbitrary identifiers, whereas the elements corresponding to attribute types are values in a fixed set, e.g., the set of reals (floats). In the acsets paper, we explain this as the difference between "combinatorial data" and "attribute data."

**Comment by epatters** [comment]
Yes, it's definitely a good idea to include the type information explicitly rather than assuming the parser can infer it from the values that appear.

**Comment by aaguinal** [comment]
To get the data necessary to serialize to this schema, it seems like we need to either:

(A) add methods that consistently assign an `_id` value and type for each `:Ob`-typed data
(B) modify the structure of the `Ob` type to support data, ID, and type information. This may look something like:
```Ob(_id::Int, data::Any, data_type::Str)```

This is necessary if we want to write out JSON formatted data using [`generate_json_acset_schema(pres::Presentation)`](https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/categorical_algebra/CSets.jl#L1241).

Which is preferred? Are there any other implementation options?
