### ISSUE TITLE
Stratification Bug while using apex(pullback(...))

### ISSUE THREAD

**Issue by Tom-Szendrey** [AlgebraicJulia/Catlab.jl#713]
While trying to use apex(pullback(...)) or ob(pullback(...)) sname is the only attribute populated
Below is what was ran to reproduce this result. Examples came from both demo notebooks

![image](https://user-images.githubusercontent.com/17088680/203599223-f1545ad0-c356-43af-b509-c320cd159ab5.png)

![image](https://user-images.githubusercontent.com/17088680/203599269-7d32b4ca-0a7c-4f0d-b777-80e6ef9be256.png)

I was able to get the expected result using:
```
res = stratify(modelATyped=>[[:strata],[:strata],[:strata],[]], # S I R D
        modelBTyped=>[[:disease], [:disease,:infect]],# Q NQ 
        typesP
) 

function stratify(petri_net1, petri_net2, type_system)
  return pullback([add_cross_terms(petri_net, type_system) for petri_net in [petri_net1, petri_net2]]) |> apex
end
```

![image](https://user-images.githubusercontent.com/17088680/203599586-0e59d2aa-35f6-4604-b3af-f25dcd5d4d96.png)

**Comment by kris-brown** [comment]
if you're following the [stratification made easy demo](https://github.com/AlgebraicJulia/ASKEM-demos/blob/master/StratificationMadeEasy.ipynb), then you are getting expected results.

The pullback you are trying to construct was called `naive_stratification` in the notebook, and it was an example intended to demonstrate that "directly" stratifying those two models will produce a model that has **no** transitions. (`nt` counts the number of transitions and the notebook shows`nt(naive_stratification) == 0`). The `stratify` helper function automates how you have to update `SIRD` and `Quarantine` the models such that the stratification that we really want is computed via Catlab's `pullback`. 

Let me know if any of the wording in that notebook can be fixed or if this doesn't actually address your problem!
