### ISSUE TITLE
Unexpected error message when adding parts

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/Catlab.jl#728]
```
g = Graph 
add_part!(g, :V)
```
this is a user error (should have been `Graph()`) results in a `StackOverflowError` in contrast to things like `rem_part!` (which results in a method not found error). If there's any way to avoid this it would make things more user friendly!

**Comment by epatters** [comment]
This should be fixable by appropriately restricting the types of `add_part(s)!`.
