### ISSUE TITLE
Error in `bfs_tree`: `T` not defined

### ISSUE THREAD

**Issue by anandijain** [AlgebraicJulia/Catlab.jl#738]
https://github.com/AlgebraicJulia/Catlab.jl/blob/7751eb7f7dbf214dea16b7a4da7dd080f14aab69/src/graphs/Searching.jl#L10-L19
```julia 
function tree(parents::AbstractVector{Int})
    n = T(length(parents))
    t = Graph(n)
    for (v, u) in enumerate(parents)
        if u > 0 && u != v
            add_edge!(t, u, v)
        end
    end
    return t
end
```
should parents be `parents::AbstractVector{T}`

**Comment by epatters** [comment]
Thanks for the report. This is the sort of thing that should have been caught by a unit test. We will remedy that.
