### ISSUE TITLE
How to find/discover things in Catlab

### ISSUE THREAD

**Issue by anandijain** [AlgebraicJulia/Catlab.jl#744]
```julia
using Catlab.Graphs
@acset_type LGraph(SchLGraph, index=[:src,:tgt,:label]) <: AbstractGraph
ERROR: LoadError: UndefVarError: `@acset_type` not defined
in expression starting at /Users/anand/.julia/dev/USCountyGraph/test/runtests.jl:151
```
how do i find where this is quickly?
apropos didn't help
```julia 
julia> apropos("@acset_type")
Catlab.DenseACSets.AnonACSet
Catlab.Graphs.PropertyGraphs.PropertyGraph
```

i realize that this isn't something that necessarily would be fixed by a change to catlab, but it would make it a lot easier to learn 
thanks!

**Comment by epatters** [comment]
I'm not sure how to fix this specifically. One thing that we'll be doing more of is splitting off functionality from Catlab into smaller packages with clearer scope, which will hopefully help with discoverability. In this case, the core acsets machinery, including this macro, is slated to be spun off.
