### ISSUE TITLE
Migrate to Julia v1.9

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#770]
The varacsets PR (#740) depends on bug fixes only available in Julia v1.9 and so we must require v1.9 before merging that PR. This will, in turn, necessitate a major release of Catlab.

As part of adopting Julia v1.9, we should use the new [package extensions](https://docs.julialang.org/en/v1/NEWS/#Package-Manager) feature to eliminate the dependency on Requires.jl.

**Comment by mehalter** [comment]
@epatters want me to put together a PR for package extensions on Catlab and dropping Requires.jl? I did this recently for AlgebraicPetri.

**Comment by epatters** [comment]
That would be wonderful, thanks!

**Comment by epatters** [comment]
Completed by #775. Thanks @mehalter!
