### ISSUE TITLE
Migrate acsets core to new standalone package

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#771]
This refers to the contents of `src/acsets`. The overtly categorical functionality, beginning with acset homomorphisms, will remain in `Catlab.CategoricalAlgebra` for now.

**Comment by mehalter** [comment]
We have SubACSets in AlgebraicPetri currently that needs to be moved. The main thing is the functionality for calculating most common ACSet. Do you think that will get migrated to the new ACSets package or still into somewhere in Catlab?

**Comment by epatters** [comment]
I'm expecting the subacsets functionality to remain in Catlab because it uses interfaces for lattices provided by `Catlab.Theories`. It would be great to upstream most-common-subacset to Catlab at some point.

**Comment by mehalter** [comment]
Ok cool that's exactly what I was thinking. I'll get a PR to migrate that over for the 0.15 release. It would be good to coincide that with AlgebraicPetri since it's removal will be a breaking change on that end. @epatters do you have a goal date for that release? Just so I have a due date in mind?

**Comment by epatters** [comment]
My hope and goal is to have this done by the end of the week.

**Comment by mehalter** [comment]
Ok awesome, I'll follow suit and get a PR together for SubACSets MCA stuff as well by the end of the week for the release
