### ISSUE TITLE
Bug in `oapply` for multispans

### ISSUE THREAD

**Issue by samuelsonric** [AlgebraicJulia/Catlab.jl#797]
Julia 1.9, Catlab v0.14.17

When I run the following lines of code, I see an error `Feet of spans are not equal: FinSet(3) != FinSet(4775367456)`.
```
using Catlab, Catlab.CategoricalAlgebra, Catlab.Programs, Catlab.WiringDiagrams

wd = @relation (x,) begin
    f(x, y)
end

span = Multispan([
    FinFunction([1, 2, 3]),
    FinFunction([1, 2, 3])])

oapply(wd, [span])
```
It looks like there is something wrong with line 52 in [this file](https://github.com/AlgebraicJulia/Catlab.jl/blob/f4eb794394b355d39209b8f814b83a9166f41c06/src/wiring_diagrams/Algebras.jl#L52). When `Ob = FinSetInt`, the function call `isassigned(junction_feet, j)` is always `true`.

**Comment by epatters** [comment]
Thanks for the report. I can also reproduce this bug on Catlab master. My guess is that it's actually a bug in ACSets.jl but we'll see.

**Comment by epatters** [comment]
Nevermind, it's a bug in the `oapply` method itself. I'm posting a fix.
