### ISSUE TITLE
Spin out DataMigrations.jl

### ISSUE THREAD

**Issue by KevinArlin** [AlgebraicJulia/Catlab.jl#842]
Insofar as data migration and chase-related stuff is the slowest part of Catlab to test by far, and insofar as the AttrMigr branch can't currently be merged without breaking Catlab compatibility with Julia 1.9, be it resolved: let's have Migrations.jl be a separate package.

Plain Kan extensions (Delta and Sigma) will stay in Catlab, so this is really talking about conjunctive, duc, and gluc migrations. I don't know Kris's stuff well enough to know whether anything around the chase can come with too, but I guess probably not since we want to be able to compute representables inside Catlab.

**Comment by epatters** [comment]
Agreed, though I would suggest DataMigrations.jl for a package name since it's a bit more descriptive.

**Comment by KevinArlin** [comment]
It's here, need to straighten out mysteries about the CI and write a little bit of docs before releasing 0.0.1 : https://github.com/AlgebraicJulia/AlgebraicDataMigrations.jl/actions/runs/6106046409
