### ISSUE TITLE
`NamedGraph` and presentations

### ISSUE THREAD

**Issue by slwu89** [AlgebraicJulia/Catlab.jl#848]
Hi @epatters, as part of thinking about more comprehensive visualizations for the queries making up data migrations I have discovered that Catlab defines a `NamedGraph` type here (https://github.com/AlgebraicJulia/Catlab.jl/blob/main/src/graphs/BasicGraphs.jl#L593) but as far as I can tell it is not used anywhere, and the docstring remarks that it can represent the graph  corresponding to a presentation of a `FinCat`.

Likewise in the graphviz integration, we have this function https://github.com/AlgebraicJulia/Catlab.jl/blob/main/src/graphics/GraphvizCategories.jl#L16 that takes a `Presentation` and visualizes it.

I propose that we make graphviz support for `NamedGraph` objects, and a new function to generate a `NamedGraph` from a `Presentation` (what should it be called?) and simplify the `to_graphviz_property_graph` for presentations. What do you think of this plan? I'm happy to work on it if you think it is a good idea.

**Comment by slwu89** [comment]
Closing this, as `to_graphviz` already works for `NamedGraph` objects, didn't spend enough time looking around.

**Comment by epatters** [comment]
Great, I love to hear it :)
