### ISSUE TITLE
`SigmaMigrationFunctor` method uses an undefined variable

### ISSUE THREAD

**Issue by neonWhiteout** [AlgebraicJulia/Catlab.jl#903]
SigmaMigrationFunctor(f,T′,T) = SigmaMigrationFunctor(f,d,T()) on line 193 of FunctorialDataMigrations.jl

**Comment by epatters** [comment]
Thanks for the report. @kris-brown, could you take a look at this one?

**Comment by kris-brown** [comment]
Hi @neonWhiteout, can you share what context you called this in? This method seems quite extraneous (no type information on the parameters) and the tests pass without it, so I'm leaning towards fixing this bug by just deleting the method. 

You could also test your code works in the branch here, which has the method deleted: https://github.com/AlgebraicJulia/Catlab.jl/pull/906
